### ISSUE TITLE
[App] 1:1 채팅 > "채팅 종료하기" 시 alert 메시지 필요

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#10]
1:1채팅 중 "채팅 종료하기" 터치 시 alert 메시지 넣어주세요.

(alert : 채팅을 종료하시겠습니까? 채팅을 종료하시면 대화내용이 모두 삭제되고, 리스트에서도 삭제됩니다.)
 “예” 선택 시 : 대화 내용과 채팅방, 채팅목록에서 해당 채팅 모두 삭제
 “아니오“ 선택 시 : 원래 화면으로 돌아옴

**Comment by ghost** [comment]
완료~
