### ISSUE TITLE
[Web] 1:1채팅 종료 후 메시지 정상 출력 안됨

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#11]
- 상황 : 1:1 채팅 시 인재쪽에서 채팅 종료를 했을 경우
- 현상
- 채팅관리 : 시스템 메시지 정상 출력 안됨
- 클릭해서 들어 갔을 경우 "종료하기" 클릭 시 정상적으로 종료(=삭제) 안됨
- 기업 홈에서도 정상적으로 삭제되어 있지 않음
- 클릭 시 채팅방에 접속중이라고 나타남

-> 대화방 내부에 있는 종료하기 클릭 시에서도 채팅방, 리스트에서 모두 삭제 필요
![1](https://f.cloud.github.com/assets/6456985/1992171/476a1eb8-84b3-11e3-8733-f99a64d103b6.png)
![2](https://f.cloud.github.com/assets/6456985/1992172/476d25b8-84b3-11e3-9875-cc7f4b40184a.png)
![3](https://f.cloud.github.com/assets/6456985/1992173/4789b55c-84b3-11e3-85e5-a36639cdb29b.png)
![4](https://f.cloud.github.com/assets/6456985/1992174/478cd214-84b3-11e3-9389-cfe61febe7d3.png)

**Comment by Soulgrapher** [comment]
수정됬어여~~
