### ISSUE TITLE
[App] 1:1채팅이 없을 경우 텍스트

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#12]
회색 텍스트가 버튼 그리드에 맞춰져야 될 것 같은데요..
혹시 그렇게 들어가면 어떤지... 확인 부탁 드립니다.

![screenshot_2014-01-24-16-19-46](https://f.cloud.github.com/assets/6456985/1992724/10cf1da8-84c8-11e3-95ee-aa6d8ac8515a.png)

**Comment by ghost** [comment]
가운데 정렬로 맞춰 놓았어요~
