### ISSUE TITLE
[App] 나를 본 기업 에서 기업 로고 위치, 감성태그 표시

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#13]
1. 나를 본 기업 리스트에서 기업 로고 위치를 가운데 정렬 해주세요.
2. 감성태그를 최대 2줄로 나올 수 있도록 해주세요.
   그리고 현재 표시된 형태는 웹에서 등록할 경우 줄바꿈한 상태가 그대로 나오는 것 같습니다.
   콤마(,)의 경우 붙여서 나올 수 있도록 해주세요.

![screenshot_2014-01-24-16-22-20](https://f.cloud.github.com/assets/6456985/1992738/75201d84-84c8-11e3-8482-7808e12defe6.png)

**Comment by ghost** [comment]
완료~
