### ISSUE TITLE
1:1 채팅 메뉴 중 "차단하기" 터치 시 alert 수정

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#14]
1:1 채팅방 메뉴 중 "차단하기" 터치 시 출력되는 alert 메시지 수정해주세요.

(기존)
"차단되었습니다."

(변경)
alert : 선택한 기업을 차단 하시겠습니까?(차단할 경우 현재 리스트에서 삭제되고, 차단기업관리 에서 확인할 수 있습니다.)
 “예” 선택 시 : 리스트에서 삭제되고, 설정>차단기업관리에서 확인 가능
 “아니오” 선택 시 : 액션 없음

**Comment by ghost** [comment]
"선택한 기업을 차단하시겠습니까? 차단할 경우 채팅 목록에서 삭제되고, 설정 메뉴의 차단기업 관리에서 확인할 수 있습니다." 라고 수정할께요.
