### ISSUE TITLE
기업 홈에서 "나를 본 기업" 카운팅이 안됨

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#15]
기업 홈에서 "나를 본 기업"이 있는 경우에도 숫자 카운팅이 안됩니다.

기존에는 카운팅이 되었는데..
차단하고 나서 다시 해제를 하니 이와 같은 현상이 발생하는 것 같습니다.

확인 부탁 드립니다.

**Comment by Soulgrapher** [comment]
다시 확인부탁드려요~!!
