### ISSUE TITLE
1:1채팅 중 기업을 차단하고, 해제 했을 경우에도 웹에는 "채팅중"이라고 표시

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#16]
1:1채팅 중 기업을 차단하고, 해제했을 경우에도 웹에는 "채팅중"이라고 표시됩니다.
모바일에서는 리스트에서 확인할 수 없습니다.

채팅중이 풀릴 수 있도록 수정 부탁 드립니다.

**Comment by Soulgrapher** [comment]
채팅중일때 기업차단을 했더라도..
기업입장에서는 채팅중이 맞는거 같습니다.
기업이 채팅을 그만해야 채팅중이 해제되는게 아닌가여???

**Comment by JinKyoung** [comment]
말씀하신 것과 같이 채팅중이 맞는 것 같습니다..

차단과 차단해제에 영향을 안 받는게 맞는것 같습니다.
클로즈 하도록 하겠습니다.
