### ISSUE TITLE
채팅관리에서 새로운 채팅 메시지를 받았을 경우 리스트와 편지함에 표시되지 않음

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#20]
채팅관리에서 새로운 채팅 메시지를 받았을 경우
1. GNB 영역의 편지함?에 N 표시 
2. 채팅 리스트에 숫자 표시

가 되어야 합니다. 수정 부탁 드립니다.

![20140127_095352](https://f.cloud.github.com/assets/6456985/2005563/c595d5c0-86ed-11e3-978d-b660116e614b.png)

**Comment by Soulgrapher** [comment]
다시 확인 부탁합니다..
전 잘 되요

**Comment by JinKyoung** [comment]
다시 하니 잘되네요 ㅠㅠ
클로즈 할께요~
