### ISSUE TITLE
[App] 회원가입 시 약관 종류 텍스트 표시 안됨

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#4]
갤럭시 노트2

"이용약관", "개인정보취급방침" 텍스트 표시 안됨
![screenshot_2014-01-22-14-25-41](https://f.cloud.github.com/assets/6456985/1991506/eaf64aaa-849c-11e3-8a08-3e049cf10459.png)

**Comment by ghost** [comment]
완료~
