### ISSUE TITLE
[App] 프로필에 가로로된 사진 등록 시 가로로 나옴

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#5]
카카오톡에서 동일한 이미지로 테스트한 결과 가로 사진도 회전에서 출력함

![screenshot_2014-01-24-11-17-56](https://f.cloud.github.com/assets/6456985/1991553/1f895086-849e-11e3-8e7e-279b068a848b.png)

**Comment by ghost** [comment]
사진이 가로인지 세로인지를 판단해 주는 이미지 라이브러리가 필요합니다. 다음 버전 개발할 때 찾아볼께요.
