### ISSUE TITLE
[App] 감성태그 입력 시 하단 안내 텍스트 수정

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#6]
텍스트 중 예시 텍스트에 대해서 아래와 같이 수정 부탁 드립니다. 

기존
(예 : 사내동호회, 휴가지원, 칼퇴근, 주2회 회식)

변경
(예 : 열정, 등산, 독서, 긍정적, 빨간색, 기독교, 배낭여행)

**Comment by ghost** [comment]
완료~
