### ISSUE TITLE
[App] 회원가입 시 감성태그 입력 영역 텍스트 수정

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#7]
회원가입 시 감성태그 입력 영역에 있는 텍스트를 아래와 같이 수정 부탁 드립니다. 

기존
(예 : 열정, 등산, 독서, 긍정적, 빨간색, 기독교, 배낭여행, 컴퓨터, 소프트웨어개발)

변경
(예 : 열정, 등산, 독서, 긍정적, 빨간색, 기독교, 배낭여행)

**Comment by ghost** [comment]
완료~
