### ISSUE TITLE
[App] 프로필 설정 > 감성태그, 근무조건에서 설정 버튼과 텍스트 겹침

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#8]
텍스트가 길어졌을 경우 버튼과 텍스트가 겹쳐집니다.
간격 등에 대한 수정 부탁 드립니다.

![screenshot_2014-01-24-13-04-22](https://f.cloud.github.com/assets/6456985/1991992/c1c40e1e-84ac-11e3-96c9-520902afce78.png)

**Comment by ghost** [comment]
완료~
