### ISSUE TITLE
[App] 기업정보 중 전화번호 터치 시 전화가 연결되지 않음

### ISSUE THREAD

**Issue by JinKyoung** [wikinet/linkyou#9]
1. 제목과 같이 기업정보에 있는 전화번호 버튼 클릭 시 
   "+025625090" 이라고 표시되며 ,없는 번호라고 안내가 나옵니다.
2. 클릭 시 바로 전화가 연결되지 않고, 아래와 같이 액션이 될 수 있도록 수정 부탁 드립니다.
   터치 시 alert 후 (alert : (기업명) 전화 연결을 하시겠습니까?)
   “예“ 선택 시 : 저장된 기업 번호로 전화 연결
   “아니오“ 선택 시 : 액션 없음

**Comment by ghost** [comment]
완료~
